<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260307145751 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE allergens_meal (allergens_id INT NOT NULL, meal_id INT NOT NULL, PRIMARY KEY (allergens_id, meal_id))');
        $this->addSql('CREATE INDEX IDX_59803994711662F1 ON allergens_meal (allergens_id)');
        $this->addSql('CREATE INDEX IDX_59803994639666D6 ON allergens_meal (meal_id)');
        $this->addSql('ALTER TABLE allergens_meal ADD CONSTRAINT FK_59803994711662F1 FOREIGN KEY (allergens_id) REFERENCES allergens (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE allergens_meal ADD CONSTRAINT FK_59803994639666D6 FOREIGN KEY (meal_id) REFERENCES meal (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE allergen DROP CONSTRAINT fk_25bf08ce639666d6');
        $this->addSql('DROP TABLE allergen');
        $this->addSql('ALTER TABLE meal DROP allergens');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, meal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_25bf08ce639666d6 ON allergen (meal_id)');
        $this->addSql('ALTER TABLE allergen ADD CONSTRAINT fk_25bf08ce639666d6 FOREIGN KEY (meal_id) REFERENCES meal (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allergens_meal DROP CONSTRAINT FK_59803994711662F1');
        $this->addSql('ALTER TABLE allergens_meal DROP CONSTRAINT FK_59803994639666D6');
        $this->addSql('DROP TABLE allergens');
        $this->addSql('DROP TABLE allergens_meal');
        $this->addSql('ALTER TABLE meal ADD allergens VARCHAR(255) NOT NULL');
    }
}
