<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260307153428 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE meal_allergen (meal_id INT NOT NULL, allergen_id INT NOT NULL, PRIMARY KEY (meal_id, allergen_id))');
        $this->addSql('CREATE INDEX IDX_41AD13BC639666D6 ON meal_allergen (meal_id)');
        $this->addSql('CREATE INDEX IDX_41AD13BC6E775A4A ON meal_allergen (allergen_id)');
        $this->addSql('ALTER TABLE meal_allergen ADD CONSTRAINT FK_41AD13BC639666D6 FOREIGN KEY (meal_id) REFERENCES meal (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meal_allergen ADD CONSTRAINT FK_41AD13BC6E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE allergens_meal DROP CONSTRAINT fk_59803994711662f1');
        $this->addSql('ALTER TABLE allergens_meal DROP CONSTRAINT fk_59803994639666d6');
        $this->addSql('DROP TABLE allergens');
        $this->addSql('DROP TABLE allergens_meal');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE allergens_meal (allergens_id INT NOT NULL, meal_id INT NOT NULL, PRIMARY KEY (allergens_id, meal_id))');
        $this->addSql('CREATE INDEX idx_59803994711662f1 ON allergens_meal (allergens_id)');
        $this->addSql('CREATE INDEX idx_59803994639666d6 ON allergens_meal (meal_id)');
        $this->addSql('ALTER TABLE allergens_meal ADD CONSTRAINT fk_59803994711662f1 FOREIGN KEY (allergens_id) REFERENCES allergens (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE allergens_meal ADD CONSTRAINT fk_59803994639666d6 FOREIGN KEY (meal_id) REFERENCES meal (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE meal_allergen DROP CONSTRAINT FK_41AD13BC639666D6');
        $this->addSql('ALTER TABLE meal_allergen DROP CONSTRAINT FK_41AD13BC6E775A4A');
        $this->addSql('DROP TABLE allergen');
        $this->addSql('DROP TABLE meal_allergen');
    }
}
